url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
author: "Marc Tremblay"
title: "Marc Tremblay" # the name of your site, e.g. ACME Corp.
tagline: "Software Developer"
about-me: "Hello! I’m Marc, a results-driven software developer with professional experience in C++ and C#, specializing in working with large, complex codebases. I’ve consistently contributed to high-impact projects by collaborating across interdisciplinary teams — most recently in the video game industry, where performance, creativity, and tight deadlines are key.<br><br>While my background is rooted in game development, I’m eager to apply my skills to new challenges in other domains. I'm particularly interested in embedded systems, firmware, robotics, and mobile development, and I’m excited to bring my problem-solving mindset and software craftsmanship to innovative teams outside of gaming.<br><br>Let’s build something impactful."
email: "marc.tremblay1995@gmail.com"
github-url: "https://github.com/tremblay95"
linkedin-url: "https://linkedin.com/in/marctremblay1995"
resume-pdf: "assets/docs/Marc Tremblay Resume.pdf"

sass:
  load_paths:
      - _sass
