url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Marc Tremblay" # the name of your site, e.g. ACME Corp.

socials:
  resume: "/assets/docs/Marc Tremblay - Resume.pdf"
  github: "https://github.com/tremblay95"
  linkedin: "https://www.linkedin.com/in/marc-tremblay-59456a133"
  email: "marc.tremblay1995@gmail.com"

sass_js_vars:
  highlight: "#009696"
  dark: "#222"
  darker: "#111"